name: 'Document CMake options'
description: 'GitHub Actions for automatically documenting all cmake options which specify the build.'
author: 'Matthias Peschke'
branding:
  icon: 'award'  
  color: 'green'
inputs:
  source_dir:
    description: 'Set the directory of the sources. Normally your github repository.'
    required: true
  option_filter:
    description: 'Specify a filter for cmake options to process. For getting options like MYLIB_SOME_OPT, set filter to MYLIB. If empty, no filter is applied.'
    required: false
    default: ''
  heading_marker:
    description: 'Markdown specifier for the heading of the section which contains the documentation of cmake build options.'
    required: false
    default: '#'
  heading_title:
    description: 'Title of the section which contains the documentation of cmake build options.'
    required: false
    default: 'Build Options'
  readme_name:
    description: 'Filename of the README file relative to source_dir'
    required: false
    default: 'README.md'

runs:
  using: 'composite'
  steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: execute py script
      run: |
        python ${{ github.action_path }}/make_doc.py --filter ${{ inputs.option_filter }} --source-dir ${{ inputs.source_dir }} --heading-marker ${{ inputs.heading_marker }} --heading-title ${{ inputs.heading_title }} --README-name ${{ inputs.readme_name }}
      shell: bash
